<?php

namespace Database\Seeders\Master;

use App\Models\JenisTindakan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class JenisTindakanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jenisTindakan = [
            [
                'kode' => 'INJ001',
                'nama' => 'Injeksi Intramuskular (IM)',
                'deskripsi' => 'Pemberian injeksi melalui otot',
                'tarif' => 30000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 20000,
                'jasa_non_paramedis' => 3000,
                'persentase_jaspel' => 70.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'INJ002',
                'nama' => 'Injeksi Intravena (IV)',
                'deskripsi' => 'Pemberian injeksi melalui pembuluh darah vena',
                'tarif' => 35000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 24000,
                'jasa_non_paramedis' => 3500,
                'persentase_jaspel' => 70.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'INF001',
                'nama' => 'Pemasangan Infus',
                'deskripsi' => 'Pemasangan jalur infus intravena',
                'tarif' => 75000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 52000,
                'jasa_non_paramedis' => 7500,
                'persentase_jaspel' => 70.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'INF002',
                'nama' => 'Lepas Infus',
                'deskripsi' => 'Pelepasan jalur infus',
                'tarif' => 25000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 17500,
                'jasa_non_paramedis' => 2500,
                'persentase_jaspel' => 70.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'KAT001',
                'nama' => 'Pemasangan Kateter',
                'deskripsi' => 'Pemasangan kateter urine',
                'tarif' => 75000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 52000,
                'jasa_non_paramedis' => 7500,
                'persentase_jaspel' => 70.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'KAT002',
                'nama' => 'Lepas Kateter',
                'deskripsi' => 'Pelepasan kateter urine',
                'tarif' => 25000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 17500,
                'jasa_non_paramedis' => 2500,
                'persentase_jaspel' => 70.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'JAH001',
                'nama' => 'Jahit Luka (1–4 jahitan)',
                'deskripsi' => 'Penjahitan luka kecil 1-4 jahitan',
                'tarif' => 75000,
                'jasa_dokter' => 45000,
                'jasa_paramedis' => 22500,
                'jasa_non_paramedis' => 7500,
                'persentase_jaspel' => 30.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'JAH002',
                'nama' => 'Lepas Jahitan (1 jahitan)',
                'deskripsi' => 'Pelepasan jahitan',
                'tarif' => 5500,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 3850,
                'jasa_non_paramedis' => 550,
                'persentase_jaspel' => 70.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'PER001',
                'nama' => 'Pemeriksaan Buta Warna',
                'deskripsi' => 'Tes pemeriksaan buta warna dengan ishihara',
                'tarif' => 25000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 17500,
                'jasa_non_paramedis' => 2500,
                'persentase_jaspel' => 70.00,
                'kategori' => 'pemeriksaan',
                'is_active' => true,
            ],
            [
                'kode' => 'PER002',
                'nama' => 'Pemeriksaan Visus Mata',
                'deskripsi' => 'Pemeriksaan ketajaman penglihatan mata',
                'tarif' => 15000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 10500,
                'jasa_non_paramedis' => 1500,
                'persentase_jaspel' => 70.00,
                'kategori' => 'pemeriksaan',
                'is_active' => true,
            ],
            [
                'kode' => 'SUR001',
                'nama' => 'Surat Keterangan Sehat',
                'deskripsi' => 'Penerbitan surat keterangan sehat',
                'tarif' => 25000,
                'jasa_dokter' => 15000,
                'jasa_paramedis' => 7500,
                'jasa_non_paramedis' => 2500,
                'persentase_jaspel' => 30.00,
                'kategori' => 'lainnya',
                'is_active' => true,
            ],
            [
                'kode' => 'NEB001',
                'nama' => 'Nebulizer',
                'deskripsi' => 'Terapi nebulizer untuk gangguan pernapasan',
                'tarif' => 100000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 70000,
                'jasa_non_paramedis' => 10000,
                'persentase_jaspel' => 70.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'LUK001',
                'nama' => 'Perawatan Luka Kecil (<5 cm)',
                'deskripsi' => 'Perawatan dan pembersihan luka kecil',
                'tarif' => 25000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 17500,
                'jasa_non_paramedis' => 2500,
                'persentase_jaspel' => 70.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'EKS001',
                'nama' => 'Ekstraksi Korpus Alienum (hidung/ telinga/ mata)',
                'deskripsi' => 'Pengangkatan benda asing dari hidung, telinga, atau mata',
                'tarif' => 50000,
                'jasa_dokter' => 30000,
                'jasa_paramedis' => 15000,
                'jasa_non_paramedis' => 5000,
                'persentase_jaspel' => 30.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'EKS002',
                'nama' => 'Ekstraksi Kuku',
                'deskripsi' => 'Pencabutan kuku yang bermasalah',
                'tarif' => 130000,
                'jasa_dokter' => 78000,
                'jasa_paramedis' => 39000,
                'jasa_non_paramedis' => 13000,
                'persentase_jaspel' => 30.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'OKS001',
                'nama' => 'Oksigenasi (2 jam pertama)',
                'deskripsi' => 'Terapi oksigen 2 jam pertama',
                'tarif' => 40000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 28000,
                'jasa_non_paramedis' => 4000,
                'persentase_jaspel' => 70.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'OKS002',
                'nama' => 'Oksigenasi per jam selanjutnya',
                'deskripsi' => 'Terapi oksigen per jam setelah 2 jam pertama',
                'tarif' => 40000,
                'jasa_dokter' => 0,
                'jasa_paramedis' => 28000,
                'jasa_non_paramedis' => 4000,
                'persentase_jaspel' => 70.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
            [
                'kode' => 'INS001',
                'nama' => 'Insisi/Eksisi Luka Besar',
                'deskripsi' => 'Tindakan insisi atau eksisi pada luka besar',
                'tarif' => 100000,
                'jasa_dokter' => 60000,
                'jasa_paramedis' => 30000,
                'jasa_non_paramedis' => 10000,
                'persentase_jaspel' => 30.00,
                'kategori' => 'tindakan',
                'is_active' => true,
            ],
        ];

        foreach ($jenisTindakan as $jenis) {
            JenisTindakan::create($jenis);
        }
    }
}
